yarnPath: .yarn/releases/yarn-3.6.0.cjs

npmScopes:
  inhibitor1217:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
